### ISSUE TITLE
Required state parameter is not sent to authorization endpoint

### ISSUE THREAD

**Issue by ngm** [sebsel/gimme-a-token#2]
According to the spec, the state parameter is required as a parameter when making authentication and authorization requests:

- https://indieauth.spec.indieweb.org/#authentication-request
- https://indieauth.spec.indieweb.org/#authorization-request

I don't think gimme-a-token is provided the state parameter - if I use it to make an auth request to my endpoint, it is missing.  (If I append a made up state value to the query string, the rest of the flow works fine.)

**Comment by sebsel** [comment]
I changed it :)
